// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQ89cROeUTK1hf1Nk2gbjKN74arfMimk',
    appId: '1:555005187369:web:b93e6e4f6558de3ea05338',
    messagingSenderId: '555005187369',
    projectId: 'autherapp-f0595',
    authDomain: 'autherapp-f0595.firebaseapp.com',
    storageBucket: 'autherapp-f0595.appspot.com',
    measurementId: 'G-1GNVHP2BVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9RPzRuzulxYF9i9B51Pm34u8jYy3t_8',
    appId: '1:555005187369:android:4b9e7721946bccbfa05338',
    messagingSenderId: '555005187369',
    projectId: 'autherapp-f0595',
    storageBucket: 'autherapp-f0595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVzMh0P4TL2wijGiC2ryfFdPsIf7p8vZY',
    appId: '1:555005187369:ios:df73ab3f062959e7a05338',
    messagingSenderId: '555005187369',
    projectId: 'autherapp-f0595',
    storageBucket: 'autherapp-f0595.appspot.com',
    iosClientId: '555005187369-kgqip810ivghd478mlpe3suepbiifn83.apps.googleusercontent.com',
    iosBundleId: 'com.example.auther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVzMh0P4TL2wijGiC2ryfFdPsIf7p8vZY',
    appId: '1:555005187369:ios:df73ab3f062959e7a05338',
    messagingSenderId: '555005187369',
    projectId: 'autherapp-f0595',
    storageBucket: 'autherapp-f0595.appspot.com',
    iosClientId: '555005187369-kgqip810ivghd478mlpe3suepbiifn83.apps.googleusercontent.com',
    iosBundleId: 'com.example.auther',
  );
}
